### ISSUE TITLE
_classes seems to check host_editing only

### ISSUE THREAD

**Issue by trident523** [theforeman/foreman_puppet#242] opened 2021-12-29 01:47 UTC
When editing a HostGroup as a role-limited user with v1.0.4 I noticed that they were unable to add new classes even with HostClass, HostGroup edit, and edit for the puppet class.

I think this is because the authorized_for is only checking for host_edit rights -- but does not consider if a user has that edit permission on a HostGroup.
https://github.com/theforeman/foreman_puppet/blob/0cd5f9269b0c0967bbd913dc88282acfb36d64f7/app/views/foreman_puppet/puppetclasses/_classes.html.erb#L9

I removed the unless as a workaround (since in the UI, they shouldn't end up on this edit page anyway) but may be missing other places where this should be there.

**Comment by ezr-ondrej** [comment] 2022-02-03 22:04
Thanks for reporting! :)
This is duplicate of #244 (I know, you've been faster, but I've already aligned a PR #251 fixing this to that ticket, so closing this one, sorry ^_^).

**Closed by ezr-ondrej** 2022-02-03 22:04 UTC
