### ISSUE TITLE
Smart Host Parameters at Host details are not being shown.

### ISSUE THREAD

**Issue by rodehoed** [theforeman/foreman_puppet#273] opened 2022-05-03 11:27 UTC
**Problem:**

Smart Host parameters (fqdn) are not visible at host detail ("Parameters"). Location paramaters are being shown though. The smart parameters are working when checking the Puppet YAML file. So basicly under water it seems to work correct.

**Workaround:**
The workaround is now to goto "[Configure] -> [Puppet ENC][Smart Class Parameters]" and look for the parameter you want to edit and add a FQDN matcher.

**Installed versions:**

- rubygem-foreman_puppet-3.0.5-1.fm3_2.el8.noarch
- foreman-3.2.0-1.el8.noarch

**Comment by nadjaheitmann** [comment] 2023-10-27 11:46
Is this a duplicate of #268?

**Closed** 2023-11-21 10:08 UTC
Labels: New Host Details Tab
