### ISSUE TITLE
 Hostgroups “nest” error 

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#219] opened 2021-11-02 08:28 UTC
https://community.theforeman.org/t/hostgroups-nest-error/25811

**Comment by ezr-ondrej** [comment] 2021-11-02 10:19
Duplicate of #189

**Closed by ezr-ondrej** 2021-11-02 10:19 UTC

**Comment by nadjaheitmann** [comment] 2021-11-02 10:26
Technically, it is still an open issue for foreman_puppet v1, isn't it ;)

**Comment by ezr-ondrej** [comment] 2021-11-04 20:19
well it's not released, but it is resolved :)
And it's a dup nevertheless :)
